global:
  scrape_interval: 15s

remote_write:
  - url: "http://metrics:9201/write"
remote_read:
  - url: "http://metrics:9201/read"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ec2'
    scrape_interval: 60s
    ec2_sd_configs:
      - refresh_interval: 120s
        region: us-east-1
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance
      - source_labels: [__meta_ec2_tag_component]
        target_label: autoscaling_group

  - job_name: 'scheduler'
    scrape_interval: 15s
    static_configs:
      - targets:
        - 'scheduler:8000' # scheduler
        - 'scheduler:9101' # cron
        - 'scheduler:9187' # postgres_exporter

